permalink: /:categories/:title/
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks

exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock', '.gitignore']
auto: true
safe: true

default_lang: en

google_tracking_id: UA-XXXXX-X

title : 100Shapes
tagline: We designs apps

production_url : http://100shapes.com
